<a href="https://colab.research.google.com/github/CarrieIsPop/EXAMEN-FINAL/blob/main/ExamenFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Examen Práctico

In [1]:
import numpy as np
import pandas as pd
import cmath

np.random.seed(0)

print('numpy version:', np.__version__)
print('pandas version:', pd.__version__)

numpy version: 2.0.2
pandas version: 2.2.2


## Parte 1: Fundamentos NumPy

In [2]:
arr = np.arange(1, 21)
print(arr)

print(arr[arr % 3 == 0])

mat = np.random.rand(5, 5)
print(mat)

print('Media:', mat.mean())
print('Desviación estándar:', mat.std())
print('Máximo:', mat.max())

print(mat.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]
Media: 0.5907662544523903
Desviación estándar: 0.2824260166721418
Máximo: 0.978618342232764
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152 0.79172504 0.52889492
 0.56804456 0.92559664 0.07103606 0.0871293  0.0202184  0.83261985
 0.77815675 0.87001215 0.97861834 0.79915856 0.46147936 0.78052918
 0.11827443]


## Parte 2: Fundamentos Pandas

In [3]:
data = {
    'Nombre': ['Ana', 'Luis', 'María', 'Pedro', 'Sofía'],
    'Edad': [20, 21, 19, 22, 20],
    'Nota_Matemáticas': [18, 15, 16, 12, 19],
    'Nota_IA': [17, 14, 18, 13, 20]
}

df = pd.DataFrame(data).set_index('Nombre')
print(df)

print(df.mean(numeric_only=True))

print(df[df['Nota_IA'] > 15])

df['Promedio'] = df[['Nota_Matemáticas','Nota_IA']].mean(axis=1)
print(df)

print(df.sort_values('Promedio', ascending=False))

        Edad  Nota_Matemáticas  Nota_IA
Nombre                                 
Ana       20                18       17
Luis      21                15       14
María     19                16       18
Pedro     22                12       13
Sofía     20                19       20
Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64
        Edad  Nota_Matemáticas  Nota_IA
Nombre                                 
Ana       20                18       17
María     19                16       18
Sofía     20                19       20
        Edad  Nota_Matemáticas  Nota_IA  Promedio
Nombre                                           
Ana       20                18       17      17.5
Luis      21                15       14      14.5
María     19                16       18      17.0
Pedro     22                12       13      12.5
Sofía     20                19       20      19.5
        Edad  Nota_Matemáticas  Nota_IA  Promedio
Nombre                        

## Parte 3: Algoritmia aplicada

In [4]:
def mayor_menor_promedio(lista):
    if not lista:
        raise ValueError('Lista vacía')
    return max(lista), min(lista), sum(lista)/len(lista)

print(mayor_menor_promedio([3,7,2,9,4]))

(9, 2, 5.0)


In [5]:
def sigmoid(x):
    x = np.array(x)
    return 1/(1+np.exp(-x))

x = np.array([-2,-1,0,1,2])
print(sigmoid(x))

[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [6]:
def clasificar(promedio):
    return 'Aprobado' if promedio >= 14 else 'Desaprobado'

df['Estado'] = df['Promedio'].apply(clasificar)
print(df)

        Edad  Nota_Matemáticas  Nota_IA  Promedio       Estado
Nombre                                                        
Ana       20                18       17      17.5     Aprobado
Luis      21                15       14      14.5     Aprobado
María     19                16       18      17.0     Aprobado
Pedro     22                12       13      12.5  Desaprobado
Sofía     20                19       20      19.5     Aprobado


Parte 4: Mini-proyecto

In [7]:
datos = {
    'Producto': ['A','B','C','D','E'],
    'Ventas_2024': [120, 340, 560, 230, 150],
    'Ventas_2025': [200, 400, 600, 300, 180]
}

df_ventas = pd.DataFrame(datos)
print(df_ventas)

df_ventas['Crecimiento (%)'] = ((df_ventas['Ventas_2025'] - df_ventas['Ventas_2024']) / df_ventas['Ventas_2024'] * 100).round(2)
print(df_ventas)

producto_max = df_ventas.loc[df_ventas['Crecimiento (%)'].idxmax()]
print('Producto con mayor crecimiento:\n', producto_max)

  Producto  Ventas_2024  Ventas_2025
0        A          120          200
1        B          340          400
2        C          560          600
3        D          230          300
4        E          150          180
  Producto  Ventas_2024  Ventas_2025  Crecimiento (%)
0        A          120          200            66.67
1        B          340          400            17.65
2        C          560          600             7.14
3        D          230          300            30.43
4        E          150          180            20.00
Producto con mayor crecimiento:
 Producto               A
Ventas_2024          120
Ventas_2025          200
Crecimiento (%)    66.67
Name: 0, dtype: object


## Parte 5: Resolución de ecuaciones

In [8]:
def resolver_lineal(a,b):
    if a==0:
        return 'Infinitas soluciones' if b==0 else 'Sin solución'
    return -b/a

print(resolver_lineal(2,4))

-2.0


In [9]:
def resolver_cuadratica(a,b,c):
    if a==0:
        return resolver_lineal(b,c)
    disc = b**2 - 4*a*c
    sqrt_disc = cmath.sqrt(disc)
    x1 = (-b + sqrt_disc)/(2*a)
    x2 = (-b - sqrt_disc)/(2*a)
    return x1,x2

print(resolver_cuadratica(1,-5,6))
print(resolver_cuadratica(1,0,1))

((3+0j), (2+0j))
(1j, -1j)
